### ISSUE TITLE
post access violation

### ISSUE THREAD

**Issue by bschuler** [elabftw/elabapy#1]
Hi!

When I try to update an experiment or item I get the following error message:
['error', 'This section is out of your reach!']

This seems to be related to an access violation in the request module.

Minimal Example:
exp = manager.get_experiment(1)
exp['title'] = 'new title'
manager.post_experiment(1,exp)

**Comment by NicolasCARPi** [comment]
Hello,

You make me realize that I didn't merge the documentation into master. Please try as the example here: http://elabftw.readthedocs.io/en/next/api.html#change-the-body-title-and-date

**Comment by bschuler** [comment]
Thanks. I tried that as well (before already). But still the same error:
['error', 'This section is out of your reach!']

It seems like I do not have the permission to post anything.

**Comment by NicolasCARPi** [comment]
Do you own the experiment you're trying to update?

**Comment by bschuler** [comment]
Yes.

**Comment by bschuler** [comment]
And the visibility is on TEAM if that matters...

**Comment by bschuler** [comment]
I also get this warning (also for all other elabapy commands): 
C:\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

but get functions still work.

**Comment by NicolasCARPi** [comment]
Yeah you can ignore the warning, it's because you have a self-signed certificate. Can you make sure that the API token in your script is the same as the one on your profile?

**Comment by bschuler** [comment]
I did. It matches. I also regenerated the key and updated the script. Same result. 
I use jupyter could this be a reason?

**Comment by NicolasCARPi** [comment]
No that is really an elabftw permission issue. You can edit the experiment through the web, right? If yes, I don't see why it wouldn't work with the API…

**Comment by bschuler** [comment]
yes in the web everything works smoothly.

**Comment by NicolasCARPi** [comment]
I tried on my side, but cannot reproduce :/

It would help if you can post your script (or part of it).

**Comment by bschuler** [comment]
import elabapy 
manager = elabapy.Manager(endpoint="https://labbook1.lbl.gov/api/v1/", token="c8c70a4....")
params = {"title": "New title", "body": "Experiment updated through API", "date": "20170415"}
manager.post_experiment(1, params )

**Comment by bschuler** [comment]
could it be a firewall thing?

**Comment by NicolasCARPi** [comment]
Can you try that? : 

~~~bash
echo 'This is some text.' > test.txt
export API_KEY="<your_api_key>"
curl -X POST -F "file=@test.txt" -H "Authorization: $API_KEY" "https://labbook1.lbl.gov/api/v1/experiments/1"
~~~

Replace <your_api_key> by your real API key of course.
At least if that doesn't work we'll know the issue is not with elabapy :)

**Comment by bschuler** [comment]
On the mac terminal it did not work:

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by NicolasCARPi** [comment]
Yeah you need to add the -k flag. curl -k -X POST ...

**Comment by bschuler** [comment]
Now I got the same result as with Python:
'This section is out of your reach!'

**Comment by NicolasCARPi** [comment]
Ok, kind of expected that. But at least we know elabapy is not the culprit. If you can edit it through the web, it should be the same through the API as it's the same function that checks for permissions… So I'm not sure how you get such an error :/

Maybe just so you can get to work you can comment out [this line](https://github.com/elabftw/elabftw/blob/master/app/classes/Api.php#L102) and [this line](https://github.com/elabftw/elabftw/blob/master/app/classes/Api.php#L122) (use `docker exec -it elabftw vi /elabftw/app/classes/Api.php`, then 

~~~vi
102G i // <Esc> 122G i // <Esc> :x 
~~~
).

**Comment by bschuler** [comment]
The two lines are now commented out but now I get the following error:
['error', "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userid' cannot be null"]

also if I add a userid:
params = {"title": "New title", "body": "Experiment updated through API", "date": "20170415", "userid": "1"}
manager.post_experiment(1, params)

I get the same result.

**Comment by NicolasCARPi** [comment]
Ok, I think I know why you get this error. This bug is in fact corrected in the `hypernext` branch but not in `master`. Edit the file `app/models/Users.php`, and after [line 356](https://github.com/elabftw/elabftw/blob/master/app/models/Users.php#L356) add:

~~~php
$this->userid = $this->userData['userid'];
~~~

Like [here](https://github.com/elabftw/elabftw/blob/hypernext/app/models/Users.php#L357).

**Comment by bschuler** [comment]
awesome. now it works! Will I need to comment out [this line](https://github.com/elabftw/elabftw/blob/master/app/classes/Api.php#L102) and [this line](https://github.com/elabftw/elabftw/blob/master/app/classes/Api.php#L122) manually every time I update?

**Comment by NicolasCARPi** [comment]
No, no, the update will completely fix this issue.
