### ISSUE TITLE
Getting an upload from the /uploads/{id} route

### ISSUE THREAD

**Issue by sherjeelshabih** [elabftw/elabapy#10]
There is no method in elabapy to get a specific uploaded item from the upload ID. I suggest adding a simple method that just accesses "/uploads/{id}" to elabapy.

I have done that in the following fork:
https://github.com/shabihsherjeel/elabapy

I hope I am not overlooking something here. I can make a pull request if this is feasible for elabapy.

**Comment by NicolasCARPi** [comment]
Hello,

Yes indeed, and because it is available from the API, it's trivial to add. Please make a pull request, I'm always happy to have contributors. Would be great if you could make also a PR for the elabdoc (`doc/api.rst` page) too so the change is complete. ;)

**Comment by sherjeelshabih** [comment]
Hi Nicolas,

Sure. No worries. :) 
I would add an example to the api doc once this is merged. Just to be sure of the final function name.
