### ISSUE TITLE
Baseapi.py's get_data attempts to decode all data received

### ISSUE THREAD

**Issue by sherjeelshabih** [elabftw/elabapy#13]
If we use the same get_data function for files that can't be parsed as json, it gives a JSON decode error. I would suggest returning requests.content or requests.text.

`data = req.json()`

This can be changed to:

`data = req.text`

This issue is in reference to the following:
https://github.com/elabftw/elabdoc/pull/10

**Comment by NicolasCARPi** [comment]
No, I would suggest creating another function that uses req.content (see https://requests.readthedocs.io/en/master/user/quickstart/#binary-response-content).

It makes sense to use req.json() as all other responses are in json.

**Comment by NicolasCARPi** [comment]
the function could be called get_binary()

**Comment by NicolasCARPi** [comment]
For the purpose of get_backup_zip, I had to implement this. So a flag `binary` now exists on `get_data` to get a binary response.

This flag has been added to `get_upload()` (for 0.5.2)

Examples with python code have also been added to the doc for `get_upload()` on https://doc.elabftw.net/api/

![2020-05-04-022727_1048x622_scrot](https://user-images.githubusercontent.com/3043706/80929765-d4aaa300-8dae-11ea-8810-10aa284eb25f.png)
