### ISSUE TITLE
`manager.get_all_items()` no longer returning all items

### ISSUE THREAD

**Issue by din14970** [elabftw/elabapy#17]
Since a recent upgrade of elabFTW, I can't pinpoint exactly when, the `get_all_items` method is no longer working as before. Now it seems only the first 16 items are returned. So I guess it is only returning the first page of results? Can someone else reproduce this?

**Comment by NicolasCARPi** [comment]
I guess this is a side effect of the new way items are requested. By default the limit is 15, and +1 to be able to show the next page button if there are more.

Anyway, the correct way would be to have pages, see for example https://developer.github.com/v3/#pagination.

This would mimic the way you access the items on the web (with a limit and an offset parameter).

At the moment to get more items you can do that:

~~~diff
diff --git a/src/controllers/ApiController.php b/src/controllers/ApiController.php
index e74d0dcc2..9e97db8e3 100644
--- a/src/controllers/ApiController.php
+++ b/src/controllers/ApiController.php
@@ -327,6 +327,7 @@ class ApiController implements ControllerInterface
         if ($this->id === null) {
             $DisplayParams = new DisplayParams();
             $DisplayParams->adjust($this->App);
+            $DisplayParams->limit = 100000;
             return new JsonResponse($this->Entity->readShow($DisplayParams, true));
         }
         $this->Entity->canOrExplode('read');
~~~

**Comment by din14970** [comment]
How should I change this on a live instance? The file appears in a number of strange filepaths e.g. `/var/lib/docker/volumes/{uuid}/_data/src/controllers/ApiController.php`.

**Comment by NicolasCARPi** [comment]
docker exec -it elabftw bash

then vi src/controllers/ApiController.php

**Comment by m6121** [comment]
I also stumbled about this problem and will use the workaround for the moment. I was wondering why it is not possible (in both elabapy but also using direct GET-requests) to change the settings inside DisplayParams by the following. Also, for some reason it does not seem to take the User Control Panel settings inside the API.

```
https://<server url>/api/v1/items?limit=100
```

**Comment by NicolasCARPi** [comment]
Now limit and offset parameters can be sent along.
