### ISSUE TITLE
how to upload file?

### ISSUE THREAD

**Issue by bschuler** [elabftw/elabapy#2]
Hi,
How can I attach a file with elabapy?

**Comment by NicolasCARPi** [comment]
Hello,

I just added this to elabapy. See [documentation](https://elabftw.readthedocs.io/en/latest/api.html#upload-a-file). I'll update the Pypi (pip) version as soon as I remember how to do it… Meanwhile you can just git clone this repo and install it from the repo, it's the same.

Regards,
~Nico
