### ISSUE TITLE
Add elements to experiment body with elabapy

### ISSUE THREAD

**Issue by NFFA-TS** [elabftw/elabapy#20]
Hello,

I'm sorry I'm a neophyte in all of this.
I am trying elabapy API and I was wondering if it is possible to update only the body of an experiment, adding elements and data without deleting the ones already present. 
Also, when I try to modify only the body of an existing experiment, without changing the title and date, it creates a new experiment instead. 
Am I missing something?

Example:
```
params = { "body": "New body" }
print(manager.post_experiment(171, params))

{'result': 'success', 'id': 172}
```
It only works if I indicate all three parameters:
```
params = { "title": "Prova", "date": 20210426, "body": "New body" }
print(manager.post_experiment(171, params))

{'result': 'success'}
```

Thank you and have a nice day!
Irene

**Comment by NicolasCARPi** [comment]
Hello,

Yes you always need to send the three parameters (it actually detects if the `date` is present). Note that this won't be the case anymore in the next version, where you'll be able to send just the title or date or body.

~Nico

**Comment by NicolasCARPi** [comment]
I'll need to update elabapy to match elabftw's api for this particular use case.

**Comment by NFFA-TS** [comment]
Thank you Nicolas, I see that you made it possible to send just the title or date or body to change any of these elements.
Anyway, I am not sure if there is now a way to add elements to the body of an experiment without replacing the body that's already there.

**Comment by NicolasCARPi** [comment]
Some sort of append function? Could be implemented, would not be very hard to do.

**Comment by NFFA-TS** [comment]
Yes, sorry, that was the purpose of my issue in the first place, I must have expressed myself badly.

**Comment by NicolasCARPi** [comment]
Please open a new issue then ;)
