### ISSUE TITLE
Possibility of sectioning Experiment body into cells

### ISSUE THREAD

**Issue by mpanighel** [elabftw/elabapy#21]
Hello, I started to use elabFTW and I am going in for it more and more.
In my particular use case I noticed the body of an Experiment could extend considerably after some time and it start to be more difficult to handle or to retrieve information through the APIs. Here is a feature proposal just to discuss its feasibility or relevance.

The body of an Experiment could be sectioned into blocks or "cells", so instead of being a single string, the body would be a list (somehow similarly to the "uploads" or "links" Experiment entries). In this case, updating the body could simply consist in the addition of an element to this list #20 .These cells could also have their own tags and attributes.
On long experiments this allows a better handling (also through APIs) thanks to the associated attributes, avoiding complicated parsing. As well as to visualize the experiment flow and identify multiple users activity.
In case the body is a list of just one element (or a string for backward compatibility), we fall back into the current situation.

In the web interface each "cell" could be displayed within a thin frame (as it is now for the body) optionally with an icon to show its attributes (see mockup image below).
![elab_cells](https://user-images.githubusercontent.com/30869713/116225802-8e361d00-a752-11eb-9cf8-ed560556a282.png)

**Comment by mpanighel** [comment]
To clarify, here is some pseudo-code that would be used with elabapy:

``` python
manager = elabapy.Manager(endpoint=endpoint, token=token)
exp = manager.get_experiment(42)
exp
```

>       {'id': '42',
>        'title': 'My title',
>        'date': '20210426',
>        'body': [{'cell_id': '1',
>                  'content': 'My first cell.',
>                  'tags': ['some tag', "another tag"],
>                  'exp_id': '42',
>                  'userid': '31',
>                  'datetime': '2021-04-26 14:10:00',
>                  'lastchange': "2021-04-26 14:10:00"}
>                ],
>        'category': 'Running',
>        ...
>        'steps': []}
> 

``` python
text = "My second cell."
exp.add_cell(text) # Or any other suitable method
exp
```

>       {'id': '42',
>        'title': 'My title',
>        'date': '20210426',
>        'body': [{'cell_id': '1',
>                  'content': 'My first cell.',
>                  'tags': ['some tag', "another tag"],
>                  'exp_id': '42',
>                  'userid': '31',
>                  'datetime': '2021-04-26 14:10:00',
>                  'lastchange': "2021-04-26 14:10:00"},
>                  {'cell_id': '2',
>                   'content': 'My second cell.',
>                   'tags': ['a new tag', "another tag"],
>                   'exp_id': '42',
>                   'userid': '31',
>                   'datetime': '2021-04-26 16:10:58',
>                   'lastchange': "2021-04-26 16:10:58"}
>                 ],
>        'category': 'Running',
>        ...
>        'steps': []}

``` python
new_text = "My new second cell."
exp.modify_cell(2, new_text) # Or any other suitable method
exp
```

>      {'id': '42',
>        'title': 'My title',
>        'date': '20210426',
>        'body': [{'cell_id': '1',
>                  'content': 'My first cell.',
>                  'tags': ['some tag', "another tag"],
>                  'exp_id': '42',
>                  'userid': '31',
>                  'datetime': '2021-04-26 14:10:00',
>                  'lastchange': "2021-04-26 14:10:00"},
>                  {'cell_id': '2',
>                   'content': 'My new second cell.',
>                   'tags': ['a new tag', "another tag"],
>                   'exp_id': '42',
>                   'userid': '31',
>                   'datetime': '2021-04-26 16:10:58',
>                   'lastchange': "2021-04-26 16:11:05"}
>                 ],
>        'category': 'Running',
>        ...
>        'steps': []}

**Comment by NicolasCARPi** [comment]
Hello,

I think this can be done with the new (4.0) metadata JSON field that exists on experiments, experiments templates, items types and items.

The body is and will stay a big string. But with the metadata field you can achieve what you want to do, and we can discuss together ways to improve it so it looks like what you describe more.

Have a look at https://demo.elabftw.net/experiments.php?mode=edit&id=3370, I have added some metadata. As you can see there is now a "Cell 1" input. Click the "Load metadata" button to see the json. I could add the "textarea" type so the input is bigger. Now from the api you can inspect really easily the metadata field and update only parts of it from your code (that makes me think that metadata is not editable by api yet, but it'll be easy to add).

That's the whole point of this metadata field, it can help extend current interface to adapt to different workflows.

Also, if your body field becomes too big, you can split your experiment in parts 1..n. No shame in that :p

**Comment by mpanighel** [comment]
Hello Nicolas,

thank you! I think it is really interesting and indeed could be close to what I was picturing. I still have to figure out how to use it properly. 

I managed to update the cell content and the cell title successfully, but I was not able to add an additional cell. Then I also changed the "extra_fields" name and now, even if the json is there, it is not previewed anymore. It is not previewed also if I create an experiment from scratch and then add the json metadata.
I would then playing around with it to understand its potentiality.

**Comment by NicolasCARPi** [comment]
Well, I still need to write the "specs"/documentation. One rule is that "extra_fields" is a special key recognized by eLab, so yeah don't remove it :p

**Comment by mpanighel** [comment]
> One rule is that "extra_fields" is a special key recognized by eLab, so yeah don't remove it :p

Ok thanks ;) I suspected it was something like that. Now I also added some more cells to play around

**Comment by mpanighel** [comment]
I think I grasped the purpose of this new metadata JSON field and I will surely going to use it to store metadata related to my Experiments. Concerning the use case of this issue, it could be possibly used in case HTML or MD code and images it contains are properly rendered in View mode, but I understand that would not be its original purpose.

As a dirt workaround, I noticed that text can be "hidden" within the body by (ab)using MD link labels:

`[//]: # (This text is visible in Edit mode but not in View Mode)`

So one could mark cells within the body using something like this:

```
[//]: # (cell {tags: ["tag 1", "tag 2"]})

First cell

[//]: # (cell {tags: ["tag 1", "tag 2"]})

Second cell
```

Clearly this approach does not allow easy handling through the APIs, and it breaks down if body is edited with Richt Text mode instead of raw mode (unless the editor is instructed they are comments).

**Comment by mpanighel** [comment]
For the sake of completeness, the HTML `div`, through its attributes, could also do the job of marking cells within the body, in this case even working seamlessly within Rich Text editor:

```
<div title="Cell #1" data-cell-id="1" data-cell-meta="{'id':1, 'tags': ['tag 1', 'tag 2']}">
    <p>First cell</p>
</div>
<div title="Cell #1" data-cell-id="2" data-cell-meta="{'id':2, 'tags': ['tag 1', 'tag 2']}">
    <p>Second cell</p>
</div>
```

Then it would be just a matter of deciding the `div` attributes design (e.g. `title` could be optional, but it is nice as its content is shown on mouse hoovering in View mode). In case it is worth, API adaptation to handle this syntax would be another matter.
