### ISSUE TITLE
File upload and image insertion into body

### ISSUE THREAD

**Issue by mpanighel** [elabftw/elabapy#22]
Hello,

I noticed that the [example code in the docs](https://doc.elabftw.net/api/#api-Entity-AddFile) for file uploading works only for text files. To upload any kind of (binary) file format (including text) to the experiment, the argument `"r"` has to be replaced with `"r+b"`, so the code would read:

```python
with open('your-file.jpg', 'r+b') as myfile:
    params = { 'file': myfile }
    print(manager.upload_to_experiment(42, params))
```
(perhaps the docs could be updated accordingly?)

If then I want to insert the image into the body of the experiment, I came up with this code:

```python
import os
def insert_image(image_path, exp_id, width="200", alt="image"):

    # Upload file
    with open(image_path, 'r+b') as myfile:
        params = { 'file': myfile }
        print(manager.upload_to_experiment(exp_id, params))

    # Get long name
    image_name = os.path.basename(image_path)
    exp = manager.get_experiment(expid)
    for item in exp['uploads']:
        if item['real_name'] == image_name:
            long_name = item['long_name']

    # Insert image into body
    params = {
        "title": "New title",
        "date": "20210503",
        "body": '<img src="app/download.php?f={}" alt="{}" width="{}"/>'.format(long_name, alt, width)
        }
    print(manager.post_experiment(exp_id, params))
```

Is there a better way to do it? Especially concerning the block  `# Get long name` (indeed `real_name` used for the matching could be not unique). Would make sense if `manager.upload_to_experiment` could return also `long_name` beside `result` ?

Thank you!

**Comment by NicolasCARPi** [comment]
Hello,

I have fixed the code example as suggested, thanks for pointing it out!

I also modified the code so that the response contains an `id` with the new upload id. You can then `GET` it to have the informations about it, including `long_name`.

I'll publish a 4.0.0-beta soon so you can try it out!

**Comment by mpanighel** [comment]
> I have fixed the code example as suggested, thanks for pointing it out!

Thank you! Just for completeness, the same issue is present also for items.

> I also modified the code so that the response contains an `id` with the new upload id. You can then `GET` it to have the informations about it, including `long_name`.
> 
> I'll publish a 4.0.0-beta soon so you can try it out!

Great, thanks!! (I tried `send_req` with `GET` on an upload but I think I miss some argument to get the info instead of the binary content).

~~By the way, still concerning docs, an alternative, more "pythonic" way of [getting an upload](https://doc.elabftw.net/api/#api-Entity-GetUpload) could be:~~

EDIT: this Python example code is already in the docs:

```python
import elabapy
manager = elabapy.Manager(endpoint="https://elab.example.org/api/v1/", token="3148")
# get binary content of upload with id 42
upl = manager.get_upload(42)
```

**Comment by NicolasCARPi** [comment]
> Great, thanks!! (I tried send_req with GET on an upload but I think I miss some argument to get the info instead of the binary content).

No I misled you. GET on `uploads` will get you the file. You need to GET the experiment/item to look for the uploaded file!

**Comment by mpanighel** [comment]
> You need to GET the experiment/item to look for the uploaded file!

Ok, got it! Thank you very much!
