### ISSUE TITLE
Circumventing self-signed certificates on NAS

### ISSUE THREAD

**Issue by din14970** [elabftw/elabapy#24]
I installed eLabFTW on a QNAP NAS which is only available on a local network. It seems however that it is not possible to make API requests to this instance because the SSL certificate on this device is self-signed and not accepted. I can't get a valid letsencrypt cert because it doesn't have a domain and is not connected to the internet. Is there a way to circumvent the SSL requirement for the API?

**Comment by NicolasCARPi** [comment]
Hello Neils, with curl use the `-k` flag, with elabapy use `verify=False` when instantiating the `elabapy.Manager` object (along with the tokend and endpoint).

I thought this was present in the documentation but can't find it now...

**Comment by din14970** [comment]
Thanks Nico, I tried this but still could not get it to work. My suspicion is that it has something to do with the way the network itself at the research institute is configured. Will have to dig deeper.
