### ISSUE TITLE
`get_items_types` broken

### ISSUE THREAD

**Issue by din14970** [elabftw/elabapy#26]
The function `get_items_types` no longer works since updating eLabFTW to v4. Currently on the latest version. Error:

```
HTTPError: 400 Client Error: Bad Request for url: https://elabftw.nielscautaerts.xyz/api/v1/items_types/
```

Other requests seem to still work fine as far as I can tell. Perhaps it would be good to add some unit tests pointing to some existing instance to ensure the API continues to work; would this be at all feasible using the demo instance?

**Comment by NicolasCARPi** [comment]
![2021-07-23-204110_848x316_scrot](https://user-images.githubusercontent.com/3043706/126826890-13de9273-8017-460d-9bfc-090875b3981d.png)
