### ISSUE TITLE
Read datafiles via API

### ISSUE THREAD

**Issue by cbuhl** [elabftw/elabapy#3]
Hi Nico,

This might not be a feature request, but I'm unable to download/read files with the API. I have a number of simple csv/tsv files in a log, and it would be excellent if I could read it with the API, so I won't have to download a copy to my desktop, but just fetch it on-the-fly from my server. 

Is this currently possible with the API?

**Comment by NicolasCARPi** [comment]
Hello,

When you do a GET to an experiment, you have the uploaded files in the json response. You also have the `long_name` of the uploaded file. So you can directly download it with https://elabftw.example.org/uploads/`long_name`.

**Comment by cbuhl** [comment]
That's excellent!
