### ISSUE TITLE
Manager.get_item should also return linked items

### ISSUE THREAD

**Issue by mrschweizer** [elabftw/elabapy#31]
The get_item method does not include linked items. [See docs](https://doc.elabftw.net/api/#api-Entity-GetItem)
This is a problem when linking equipment databases in templates, for example. There is no way to retrieve this information from a template or experiment. Without this option the add_link_to_experiment funktion is not really useful.

**Comment by mrschweizer** [comment]
This might be related to this issue #7

**Comment by NicolasCARPi** [comment]
Hello, thanks for the report, I'll look into it!

**Comment by timvgl** [comment]
It would be helpful if links, steps and metadata from a template could be downloaded with get_template.

**Comment by NicolasCARPi** [comment]
API v2 adresses these issues (currently in development but will be there for next major elabftw release).
