### ISSUE TITLE
get_all_items() returns subset of get_item()

### ISSUE THREAD

**Issue by JAC28** [elabftw/elabapy#32]
When retrieving all database items with get_all_items() I get a dict of 19 entries. However, if I select one item by its ID and use get_item() the function returns 35 entries. If this beahviour is by choice, I would suggest a hint in the documentation of the API ([https://doc.elabftw.net/api/#api-Entity-GetItem](https://doc.elabftw.net/api/#api-Entity-GetItem)) since some listed keys , e.g. elabid are missing with the get_all_items() command. 
For both cases the keys are listed below. 
|                 | 'id' | 'team' | 'title' | 'date' | 'body' | 'rating' | 'category' | 'locked' | 'lockedby' | 'lockedwhen' | 'userid' | 'canread' | 'available' | 'canwrite' | 'lastchange' | 'elabid' | 'metadata' | 'lastchangeby' | 'is_bound' | 'events_item_id' | 'events_id' | 'up_item_id' | 'has_attachment' | 'next_step' | 'category_id' | 'color' | 'fullname' | 'recent_comment' | 'has_comment' | 'bookable' | 'tags' | 'tags_id' | 'uploads' | 'links' | 'steps' |
|-----------------|------|--------|---------|--------|--------|----------|------------|----------|------------|--------------|----------|-----------|-------------|------------|--------------|----------|------------|----------------|------------|------------------|-------------|--------------|------------------|-------------|---------------|---------|------------|------------------|---------------|------------|--------|-----------|-----------|---------|---------|
| get_item()      | x    | x      | x       | x      | x      | x        | x          | x        | x          | x            | x        | x         | x           | x          | x            | x        | x          | x              | x          | x                | x           | x            | x                | x           | x             | x       | x          | x                | x             | x          | x      | x         | x         | x       | x       |
| get_all_items() | x    |        | x       | x      |        | x        | x          | x        |            |              | x        | x         |             | x          | x            |          |            |                |            |                  |             | x            | x                | x           | x             | x       | x          | x                | x             | x          |        |           |           |         |         |

elabapy version: 0.8.2
eLabFTW version: 4.2.4

**Comment by NicolasCARPi** [comment]
Hello,

This is just a consequence of how things are queried internally, and the differences are related to performance considerations (we don't select things that are not used/shown in the end). I will see if this can be improved or better documented.

**Comment by JAC28** [comment]
Hello, 
thank you for the explanation. I was quite confused when my script worked just fine with one item and stopped working when changing to the similar "get_all_items()" function. In my case I have tried to get the _elabid_. 
Maybe it is possible to indicate the subset of returned parameters within the documentation by an asterix or by adding a column for both functions similar to the table in my initial comment. 
Best regards, 
Jacob

**Comment by NicolasCARPi** [comment]
Yes, the documentation is the same for "get all" or "get one" so this is confusing. Adding a note about it will be helpful.
