### ISSUE TITLE
Document examples of query parameters

### ISSUE THREAD

**Issue by garritfra** [elabftw/elabapy#33]
The documentation mentions [Query Parameters](https://doc.elabftw.net/api/v1/#api-Entity-GetExperiment), though there are no examples how they are consumed by the library.

Relevant code section:
https://github.com/elabftw/elabapy/blob/ccb3f7a3abc043e3fbac5e0bd9a1c34aaab18c61/elabapy/Manager.py#L27

Thanks for your work on this library!

**Comment by NicolasCARPi** [comment]
Hello,

[apiv2 doc](https://doc.elabftw.net/api/v2/#/Experiments/read-experiments) is more verbose:
![2022-10-18-125624_652x856_scrot](https://user-images.githubusercontent.com/3043706/196411380-0faee7fd-ffb6-4c9f-a977-150b49ca8287.png)

That reminds me that I have to do something about elabapy and the v2... Note sure if the auto-generated code from the openapi specs will work fine.
