### ISSUE TITLE
post_experiment() method not updating experiment

### ISSUE THREAD

**Issue by RobertMende** [elabftw/elabapy#34]
Hello,

I have a problem with the post_experiment() method. It won't update the specified experiment, but will rather create a new one. I ran the following code: 

```

import elabapy
from requests.exceptions import HTTPError
from config import API_KEY, ENDPOINT;

manager = elabapy.Manager(endpoint=ENDPOINT, verify=False, token=API_KEY);

parameters={"title": "TestAPI", "body": "This is a test"};
newID=manager.create_experiment()["id"]; # create new experiment, store ID to update the experiment later
print(f"New ID: "+str(newID));
postID=manager.post_experiment(newID, params=parameters)["id"]; # update experiment's title and body as specified in "parameters" variable
print(f"ID of updated Experiment:"+str(postID)); 
response=manager.get_experiment(postID);
print("title: "+response["title"]);

```

Console output was as follows: 

> New ID: 137 # id of experiment created by create_experiment()
> ID of updated Experiment:138 # post_experiment() creates a new experiment
> title: Untitled # obviously no update to experiment no. 138 

So, all in all, the post_experiment() method creates a new experiment and won't update it according to the params argument. Am I missing something here? I am using version 0.8.2, with python 3.10.

Best regards,
Robert

**Comment by NicolasCARPi** [comment]
Hello,

No, it works fine:

~~~python
parameters = {"title": "TestAPI", "body": "This is a test"}
newID = manager.create_experiment()["id"] 
print(f"New ID: {newID}")
manager.post_experiment(newID, params=parameters)
~~~

And go to the web interface for the ID, and it will have the updated title and body.

A few notes:

* I modified the line to show the new id with correct fstring usage
* python doesn't have `;` at the end of lines
* use syntax highlighting in your code snippet by adding `~~~python`
* `post_experiment()` doesn't return an `id`
* apiv1 is deprecated and apiv2 is the future: https://doc.elabftw.net/api/v2/ (but no python lib for now)
* apiv1 will still work in version 4.4.0 though

**Comment by RobertMende** [comment]
Hello,

thanks for your response. If the code works fine for you, the request is apparently handled in the wrong way by the API, because `post_experiment()` definitely returns an `id` for me.

**Comment by NicolasCARPi** [comment]
That's because in v1 there is no distinction: it uses POST both for creating something and updating something. Whereas v2 uses PATCH method. So if you get an ID back it's because the params were not detected and it created an entry. You can see [at this line](https://github.com/elabftw/elabftw/blob/5294c2e74c7dd5c3fd6a446a158a6828a0e86ee9/src/controllers/Apiv1Controller.php#L953) that it just sends a result, with no id.

Anyway, if it works for me, it should work for you, too!
