### ISSUE TITLE
APIv2 support

### ISSUE THREAD

**Issue by BenediktBurger** [elabftw/elabapy#35]
What is the plan about the APIv2 version?
Do you want to include it in here or somewhere else?

I have to transfer some experiments via API (old server cannot be upgraded to a current version) and want to use the new API in order to copy all details (filenames etc.).
While at it, I could also share my workings with the community.

**Comment by NicolasCARPi** [comment]
Apiv2 is described via an openapi file. https://github.com/swagger-api/swagger-codegen can generate a client automatically, so I believe it might be a good idea to use that. Haven't got around to it yet.

**Comment by BenediktBurger** [comment]
In the meantime, I work on a similar API in my [APIv2 branch](https://github.com/bmoneke/elabapy/tree/APIv2). There I write some methods to copy experiments/items from one server (APIv1) to another (APIv2), as we need those.

Just in case somebody is interested in those.

**Comment by NicolasCARPi** [comment]
ApiV2 python lib is now available on this repo: https://github.com/elabftw/elabapi-python/
