### ISSUE TITLE
Unverified HTTPS request error

### ISSUE THREAD

**Issue by TheGreatFox** [elabftw/elabapy#5]
Issue: Most commands with elabapy will return the following error:

> C:\Users\username\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning

The server does have an official certificate (not self-signed) and passes all of the standard SSL verification tests. I prefer not to suppress warnings and I do get questions from users regarding this error. 

Not having experience in webapp design, I guess the issue originates whenever there is a requests.{post,get,etc.}. Looking over their documentation, it looks like it only needs a verification: 
```
http = urllib3.PoolManager(
...     cert_reqs='CERT_REQUIRED',
...     ca_certs=certifi.where())
```

Also related:
https://stackoverflow.com/questions/32296255/how-to-pass-data-to-urllib3-post-request-method?rq=1

Python installation: Anaconda 5.0.1
OS: Windows 10
eLabFTW version: 2.0.7
Installation: Docker

**Comment by NicolasCARPi** [comment]
Hello,

Maybe the script can't access the OS's certificates and thus can't verify the certificate. Users need to follow this guide: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl

Regards,
~Nico

**Comment by TheGreatFox** [comment]
Hei Nico,

Okay, so I checked our Anaconda installation and we are using the certifi module, which includes the Mozilla’s root certificate bundle. Output of certifi.where() yields: 
> C:\\ProgramData\\Anaconda3\\lib\\site-packages\\certifi\\cacert.pem

But it looks like cross-platform certificate verification is a major issue, particularly on Windows (see below): 
https://www.python.org/dev/peps/pep-0543/
https://gitlab.com/alelec/python-certifi-win32
https://github.com/kennethreitz/requests/issues/2966

So I will just close this issue since it seems, after investigation, to be outside the scope of elabapy. I'll just update our documentation and ask users to use Linux systems when possible. I guess the only actual solution is to wait for PEP-543 to be implemented (who knows) and then wait for the libraries to update accordingly.
