### ISSUE TITLE
Linked items not retrieved by get_item

### ISSUE THREAD

**Issue by fbertaux** [elabftw/elabapy#7]
Hello,

Unless I'm wrong, it seems that the get_item method does not retrieve linked items.
But it might be at the level of the web interface ?

François

**Comment by NicolasCARPi** [comment]
Hello,

Indeed they are not retrieved. Fortunately, it was very easy to add (see [commit](https://github.com/elabftw/elabftw/commit/76a58ef451eed7c6556956ffe21600100098ece4)), so I added the linked items and the steps to the answer :)

~Nico

**Comment by fbertaux** [comment]
Great, thanks !
